# Generated by Django 2.1 on 2020-04-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('ACTION', 'Action'), ('DRAMA', 'Drama')], max_length=6)),
            ],
            options={
                'verbose_name': 'Listings',
                'verbose_name_plural': 'Listings',
            },
        ),
    ]
