# Generated by Django 2.1 on 2020-04-29 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listings',
        ),
    ]
